opencctv-web/config/routes.rb
Rails.application.routes.draw do

  resources :analytic_servers

  resources :analytic_instance_streams do
    resources :analytic_instance_stream_configs do
    end
  end

resources :analytic_instances do
  resources :analytic_instance_configs do
  end
end
  get 'test/createTest', to: "test#createTest"
  get 'test/clearTest'

  get 'mobile_notifications/index'

  get 'mobile_notifications/new'

  get 'mobile_notifications/create'

  get 'mobile_notifications/edit'

  get 'mobile_notifications/update'

  get 'google_projects/index'

  get 'google_projects/new'

  get 'google_projects/show'

  get 'google_projects/edit'

  get 'api_sessions/sign_in'

  get 'api_sessions/sign_out'

  get 'session/sign_out'

  get 'session/sign_in'

  get  '/org/indexUser', to: "orgs#indexUser", as: 'org_users'
  delete  '/org/removeUser/:user_id', to: "orgs#removeUser", as: 'org_remove_user'

  post '/orgs/login/:org_id', to: "orgs#loginAsOrg", as: 'login_as_org'
  delete '/orgs/login', to: "orgs#loginAsUser", as: 'login_as_user'

  post '/org_group_users/:group_user_id/:org_user_id', to: "org_group_users#create", as: 'org_group_user'
  delete '/org_group_users/:group_user_id/:org_user_id', to: "org_group_users#destroy", as: 'destroy_org_group_user'

  post '/requests/:org_id', to: "requests#create", as: 'new_org_request'
  get  '/requests/admin', to: "requests#indexAdmin", as: 'org_requests'

  resources :requests

  resources :group_users do
    resources :vmses do
    end
  end

  resources :group_users do
    resources :analytic_instances do
    end
  end

  resources :group_users do
    resources :notifications do
    end
  end

  devise_for :users

  resources :group_users

  resources :orgs

  resources :notifications

  resources :vms_connectors

  resources :vmses do
    resources :cameras do
      resources :streams
    end
  end

  resources :analytics do
    resources :analytic_input_streams
  end

  get '/analytic_instance/:id/start', to: "analytic_instances#startAnalytic", as: 'start_analytic_instance'
  get '/analytic_instance/:id/stop', to: "analytic_instances#stopAnalytic", as: 'stop_analytic_instance'

  resources :analytic_instances do
    resources :analytic_instance_streams
  end

  resources :open_cctv_servers

  get 'about/index'

  root 'about#index'

  get '/download/vms_connector/:filename' => 'download#vms_connector', as: :vms_connector_download

  get '/download/analytic/:filename' => 'download#analytic', as: :analytic_download

  get '/open_cctv_servers/:id/start' => 'open_cctv_servers#start_server', as: :open_cctv_servers_start

  get '/open_cctv_servers/:id/stop' => 'open_cctv_servers#stop_server', as: :open_cctv_servers_stop

  get '/open_cctv_servers/:id/restart' => 'open_cctv_servers#restart_server', as: :open_cctv_servers_restart

  post '/api/google_tokens/register'   => 'google_tokens#register'
  post '/api/google_tokens/deregister' => 'google_tokens#deregister'

  post '/api/users/sign_in'  => 'api_sessions#sign_in'
  post '/api/users/sign_out' => 'api_sessions#sign_out'

  resources :google_projects
  resources :mobile_notifications

end

opencctv-web/app/models/org.rb
class Org < ActiveRecord::Base

 # belongs_to :user

  has_many :group_users, dependent: :destroy
  has_many :requests, dependent: :destroy

  has_many :org_users, dependent: :destroy
  has_many :users, through: :org_users
end

opencctv-web/app/controllers/orgs_controller.rb
class OrgsController < ApplicationController
  before_action :set_org, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :isOrganizationPageAdmin?, only: [:edit, :update, :destroy, :indexUser, :removeUser]
  respond_to :html

  def index
    @orgs = Org.joins(:users).where(:users => {:id => current_user.id})
    respond_with(@orgs)
  end

  def show
    @group_users = @org.group_users
    respond_with(@org)
  end

  def new
    @org = Org.new
    respond_with(@org)
  end

  def edit
  end

  def create
    @org = Org.new(:title => params[:org][:title], :detail => params[:org][:detail], :password => params[:org][:password],
                    :created_by => current_user.id)
    if @org.save
      @org_user = @org.org_users.create(:user_id => @org.created_by)

      @group_user = @org.group_users.create(:title => 'Organization admin', :detail => 'This group is used for managing this organization.',
                                            :role_id => ApplicationController::ROLE_ORGANIZATION_ADMIN)

      @group_user.org_group_users.create(:org_user_id => @org_user.id)

      setSessionOrganizationId(@org.id.to_s)

    else
      flash[:error] = 'Cannot create an organization.'
    end
    respond_with(@org)
  end

  def update
    @org.update(org_params)
    respond_with(@org)
  end

  def destroy

    @org.destroy

    if @org.id.to_s == session[:org_id]
      setSessionOrganizationId(nil)
    end

    respond_with(@org)
  end

  def loginAsOrg
    setSessionOrganizationId(params[:org_id].to_s)
    redirect_to :back
  end

  def loginAsUser
    setSessionOrganizationId(nil)
    redirect_to root_path
  end

  def indexUser
    @org_users = User.joins(:orgs).where(:orgs => {:id => session[:org_id]})
  end

  def removeUser
    @org_user = OrgUser.where(:org_id => session[:org_id], :user_id => params[:user_id]).first()

    if @org_user.nil? or @org_user.blank?
      flash[:error] = 'Cannot remove user.'
    else
      @org_user.destroy

      flash[:notice] = 'User was removed.'
    end

    redirect_to org_users_path
  end

  private
    def set_org
      @org = Org.find(params[:id])
    end

    def org_params
      params.require(:org).permit(:title, :detail, :password)
    end
end

opencctv-web/app/helpers/orgs_helper.rb
module OrgsHelper



end

opencctv-web/app/views/orgs/_form.html.erb
<%= form_for(@org) do |f| %>
  <% if @org.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@org.errors.count, "error") %> prohibited this org from being saved:</h2>

      <ul>
      <% @org.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_area :detail %>
  </div>
  <div class="field">
    <%#= f.label :password %><br>
    <%#= f.text_field :password %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-success btn-mini" %>
    <%= link_to 'Cancel', @org, :class => "btn btn-danger" %>
  </div>
<% end %>

opencctv-web/app/views/orgs/_info.html.erb
<div class="container">
  <h1>
    Organization information

    <a href="<%= edit_org_path(@org) %>" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span>
      Edit</a>

  </h1>


  <p>
    <strong>Title:</strong>
    <%= @org.title %>
  </p>

  <p>
    <strong>Detail:</strong>
    <%= @org.detail %>
  </p>

</div>

opencctv-web/app/views/orgs/edit.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Organizations', orgs_path %></li>
    <li class="active">Edit organization</li>
  </ol>
</div>

<div class="container">
  <h1>Editing organization</h1>
  <%= render 'form' %>
</div>

opencctv-web/app/views/orgs/index.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Home', root_path %></li>
    <li class="active">Organizations</li>
  </ol>
</div>

<div class="container">
  <h1>
    Listing organizations
    <a href="<%= new_org_path %>" class="btn btn-success"> <span class="glyphicon glyphicon-upload"></span>
      Create new organization</a>
  </h1>


  <% if @orgs.empty? %>
      <p>

      <div class="alert alert-warning">
        Currently no organization are created with the system.
      </div>
      </p>
  <% else %>
      <div class="media">
        <table class="table table-hover">

          <thead>
          <tr>
            <th>#</th>
            <th>Title</th>
            <th>Detail</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% i = 1 %>
          <% @orgs.each do |org| %>
              <tr>
                <td><%= i %></td>
                <td><%= org.title %></td>
                <td><%= org.detail %></td>

                <% if session[:org_id] == org.id.to_s %>

                    <td><%= 'Logged-in' %></td>

                <% else %>

                    <td><%= link_to 'Login', login_as_org_path(org.id), :method => :post %></td>

                <% end %>

                <td><%= link_to 'Show', org, :class => "btn btn-xs btn-default" %></td>
                <td><%= link_to 'Edit', edit_org_path(org), :class => "btn btn-xs btn-warning" %></td>
                <td><%= link_to 'Destroy', org, method: :delete, :class => "btn btn-xs btn-danger", data: {confirm: 'Are you sure?'} %></td>
              </tr>
              <% i = i + 1 %>
          <% end %>


          </tbody>
        </table>
      </div>
  <% end %>
</div>

opencctv-web/app/views/orgs/indexUser.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Home', root_path %></li>
    <li class="active">Organizations</li>
  </ol>
</div>

<div class="container">
  <h1>
    Listing organization users
  </h1>


  <% if @org_users.empty? %>
      <p>

      <div class="alert alert-warning">
        Currently no users are allowed to this organization.
      </div>
      </p>
  <% else %>
      <div class="media">
        <table class="table table-hover">

          <thead>
          <tr>
            <th>#</th>
            <th>Email</th>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% i = 1 %>
          <% @org_users.each do |org_user| %>
              <tr>
                <td><%= i %></td>
                <td><%= org_user.email %></td>
                <td><%= org_user.fullName %></td>
                <td><%= link_to 'Remove', org_remove_user_path(org_user.id), method: :delete, :class => "btn btn-xs btn-danger", data: {confirm: 'Are you sure?'} %></td>
              </tr>

              <% i = i + 1 %>
          <% end %>
          </tbody>
        </table>
      </div>
  <% end %>
</div>

opencctv-web/app/views/orgs/new.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Organizations', orgs_path %></li>
    <li class="active">New organization</li>
  </ol>
</div>

<div class="container">
  <h1>Create a new organization</h1>

  <%= render 'form' %>
</div>

opencctv-web/app/views/orgs/show.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Organizations', orgs_path %></li>
    <li class="active">Organization</li>
  </ol>
</div>

<%= render 'info' %>

<div class="container">
  <h3>
    All created groups
    <% if session[:org_id] == params[:id].to_s %>
        <a href="<%= new_group_user_path %>" class="btn btn-success"> <span class="glyphicon glyphicon-upload"></span> Create a
          group</a>
    <% end %>
  </h3>


  <br/>

  <div class="media">
    <% if @group_users.empty? %>
        <div class="alert alert-warning">
          Currently no groups are created with this organization.
        </div>
    <% else %>

        <table class="table table-hover">
          <thead>
          <tr>
            <th>#</th>
            <th>Title</th>
            <th>Detail</th>

            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% i = 1 %>
          <% @group_users.each do |group_user| %>
              <tr>
                <td><%= i %></td>
                <td><%= group_user.title %></td>
                <td><%= group_user.detail %></td>
                <% if session[:org_id] == params[:id].to_s %>
                    <td><%= link_to 'Show', group_user, :class => "btn btn-xs btn-default" %></td>
                    <td><%= link_to 'Edit', edit_group_user_path(group_user), :class => "btn btn-xs btn-warning" %></td>
                    <td><%= link_to 'Destroy', group_user, method: :delete, :class => "btn btn-xs btn-danger", data: {confirm: 'Are you sure?'} %></td>
                <% end %>
              </tr>
              <% i = i + 1 %>
          <% end %>
          </tbody>
        </table>

    <% end %>
  </div>
</div>