opencctv-web/config/routes.rb
Rails.application.routes.draw do

  resources :analytic_servers

  resources :analytic_instance_streams do
    resources :analytic_instance_stream_configs do
    end
  end

resources :analytic_instances do
  resources :analytic_instance_configs do
  end
end
  get 'test/createTest', to: "test#createTest"
  get 'test/clearTest'

  get 'mobile_notifications/index'

  get 'mobile_notifications/new'

  get 'mobile_notifications/create'

  get 'mobile_notifications/edit'

  get 'mobile_notifications/update'

  get 'google_projects/index'

  get 'google_projects/new'

  get 'google_projects/show'

  get 'google_projects/edit'

  get 'api_sessions/sign_in'

  get 'api_sessions/sign_out'

  get 'session/sign_out'

  get 'session/sign_in'

  get  '/org/indexUser', to: "orgs#indexUser", as: 'org_users'
  delete  '/org/removeUser/:user_id', to: "orgs#removeUser", as: 'org_remove_user'

  post '/orgs/login/:org_id', to: "orgs#loginAsOrg", as: 'login_as_org'
  delete '/orgs/login', to: "orgs#loginAsUser", as: 'login_as_user'

  post '/org_group_users/:group_user_id/:org_user_id', to: "org_group_users#create", as: 'org_group_user'
  delete '/org_group_users/:group_user_id/:org_user_id', to: "org_group_users#destroy", as: 'destroy_org_group_user'

  post '/requests/:org_id', to: "requests#create", as: 'new_org_request'
  get  '/requests/admin', to: "requests#indexAdmin", as: 'org_requests'

  resources :requests

  resources :group_users do
    resources :vmses do
    end
  end

  resources :group_users do
    resources :analytic_instances do
    end
  end

  resources :group_users do
    resources :notifications do
    end
  end

  devise_for :users

  resources :group_users

  resources :orgs

  resources :notifications

  resources :vms_connectors

  resources :vmses do
    resources :cameras do
      resources :streams
    end
  end

  resources :analytics do
    resources :analytic_input_streams
  end

  get '/analytic_instance/:id/start', to: "analytic_instances#startAnalytic", as: 'start_analytic_instance'
  get '/analytic_instance/:id/stop', to: "analytic_instances#stopAnalytic", as: 'stop_analytic_instance'

  resources :analytic_instances do
    resources :analytic_instance_streams
  end

  resources :open_cctv_servers

  get 'about/index'

  root 'about#index'

  get '/download/vms_connector/:filename' => 'download#vms_connector', as: :vms_connector_download

  get '/download/analytic/:filename' => 'download#analytic', as: :analytic_download

  get '/open_cctv_servers/:id/start' => 'open_cctv_servers#start_server', as: :open_cctv_servers_start

  get '/open_cctv_servers/:id/stop' => 'open_cctv_servers#stop_server', as: :open_cctv_servers_stop

  get '/open_cctv_servers/:id/restart' => 'open_cctv_servers#restart_server', as: :open_cctv_servers_restart

  post '/api/google_tokens/register'   => 'google_tokens#register'
  post '/api/google_tokens/deregister' => 'google_tokens#deregister'

  post '/api/users/sign_in'  => 'api_sessions#sign_in'
  post '/api/users/sign_out' => 'api_sessions#sign_out'

  resources :google_projects
  resources :mobile_notifications

end

opencctv-web/app/models/analytic_instance.rb
class AnalyticInstance < ActiveRecord::Base
  belongs_to :analytic
  has_many :analytic_instance_streams, dependent: :destroy
  has_many :streams, through: :analytic_instance_streams
  has_many :analytic_instance_configs, dependent: :destroy

  belongs_to :user
  belongs_to :group_user

  #has_many :group_cans, dependent: :destroy
  #has_many :group_users, through: :group_cans

  validates :analytic_id, presence: true
  validates :name, presence: true
end

opencctv-web/app/controllers/analytic_instances_controller.rb
class AnalyticInstancesController < ApplicationController

  before_action :authenticate_user!

  before_action :set_analytic_instance, only: [:show, :edit, :update, :destroy, :startAnalytic, :stopAnalytic]
  before_action :setGroupList, only: [:index, :new]
  respond_to :html

  include OpenCctvServersHelper

  # GET /analytic_instances
  def index

    if isOrganization?
      @analytic_instances = AnalyticInstance.where(group_user_id: @groupList)

    else
      @analytic_instances = AnalyticInstance.where(user_id: current_user.id)

    end

    respond_with(@analytic_instances)
  end

  # GET /analytic_instances/1
  def show
    @analytic_configs = AnalyticInstanceConfig.where(analytic_instance_id: @analytic_instance.id)
    respond_with(@analytic_instance)
  end

  # GET /analytic_instances/new
  def new
   # @notifications = Notification.where(:group_user_id => @groupList)
    @analytic_instance = AnalyticInstance.new
    respond_with(@analytic_instance)
  end

  # GET /analytic_instances/1/edit
  def edit
  end

  # POST /analytic_instances
  def create

    if isOrganization?
      @analytic_instance = AnalyticInstance.new(:name => params[:analytic_instance][:name],
                                                :description => params[:analytic_instance][:description],
                                                :analytic_id => params[:analytic_instance][:analytic_id],
                                                :notification_id => params[:analytic_instance][:notification_id],
                                                #:user_id => current_user.id,
                                                :group_user_id => params[:analytic_instance][:group_user_id])

      @analytic_instance.save

      if (!@analytic_instance.errors.any?)
        flash[:notice] = 'Successfully created analytic instance.'
        redirect_to group_user_analytic_instance_path(params[:analytic_instance][:group_user_id], @analytic_instance)
      else
        puts(@analytic_instance.errors)
        flash[:error] = 'Cannot created analytic instance.'
        redirect_to :back
      end

    else
      @analytic_instance = AnalyticInstance.new(:name => params[:analytic_instance][:name],
                                                :description => params[:analytic_instance][:description],
                                                :analytic_id => params[:analytic_instance][:analytic_id],
                                                :notification_id => params[:analytic_instance][:notification_id],
                                                :user_id => current_user.id)
      @analytic_instance.save

      respond_with(@analytic_instance)
    end


    #save  first analytic configs
    @analytic_configs = Analytic.joins(:analytic_configs).where(analytics: {id: @analytic_instance.analytic_id}).select('analytic_configs.name, analytic_configs.fileName, analytic_configs.data')
    analytic_config_array = Array.new
    @analytic_configs.each do |analytic_config|
      analytic_instance_config_db = AnalyticInstanceConfig.new
      analytic_instance_config_db.name = analytic_config.name
      analytic_instance_config_db.fileName = analytic_config.fileName
      analytic_instance_config_db.data = analytic_config.data
      @analytic_instance.analytic_instance_configs.push(analytic_instance_config_db)
    end

  end

  # PATCH/PUT /analytic_instances/1
  def update
    @analytic_instance.update(analytic_instance_params)

    if isOrganization?
      redirect_to group_user_analytic_instance_path(params[:analytic_instance][:group_user_id], @analytic_instance)
    else
      respond_with(@analytic_instance)
    end

  end

  # DELETE /analytic_instances/1
  def destroy
    @analytic_instance.destroy
    respond_with(@analytic_instance)
  end


  def startAnalytic
    @openCctvServer = OpenCctvServer.first()
    @openCctvServer.port = 4445
    msg_reply = sendToServerWithData(@openCctvServer,"StartAnalytic",@analytic_instance.id, @analytic_instance.analytic_server_id)

    if(msg_reply[:type].eql? 'Error')
      flash[:error] = "#{msg_reply[:content]}"
    else
      flash[:notice] = "Start request was sent"
      @analytic_instance.update(status: '1') # 0 = stop
    end

    redirect_to :back
  end


  def stopAnalytic
    @openCctvServer = OpenCctvServer.first()
    @openCctvServer.port = 4445
    msg_reply = sendToServerWithData(@openCctvServer,"StopAnalytic",@analytic_instance.id, @analytic_instance.analytic_server_id)

    if(msg_reply[:type].eql? 'Error')
      flash[:error] = "#{msg_reply[:content]}"
    else
      flash[:notice] = "Stop request was sent"
      @analytic_instance.update(status: '1') # 0 = stop
    end

    redirect_to :back
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_analytic_instance

    if isOrganization?
      #Protecting user is not in group but try to show
      # @vms = Vms.where(:id => params[:id],
      #                 :group_user_id =>  GroupUser.joins(:org_users)
      #                                       .where(:org_id => session[:org_id],
      #                                              :org_users => {:user_id => current_user.id},
      #                                             :group_users => {:id => params[:group_user_id]}).pluck(:group_user_id)).first()

      params[:group_user_id].nil? ?
          @analytic_instance = AnalyticInstance.where(:id => params[:id], :group_user_id => params[:analytic_instance][:group_user_id]).first()
      : @analytic_instance = AnalyticInstance.where(:id => params[:id], :group_user_id => params[:group_user_id]).first()
    else
      @analytic_instance = AnalyticInstance.where(:id => params[:id], :user_id => current_user.id).first()
    end

  end

  def setGroupList # Current group per user, per org
    if isOrganization?
      @groupList = GroupUser.getGroupUserList(session[:org_id], current_user.id)
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def analytic_instance_params
    params.require(:analytic_instance).permit(:name, :description, :analytic_id, :notification_id, :group_user_id, :analytic_server_id)
  end
end

opencctv-web/app/helpers/analytic_instances_helper.rb
module AnalyticInstancesHelper
end

opencctv-web/app/views/analytic_instances/_form.html.erb
<%= form_for(@analytic_instance) do |f| %>

    <!--Report errors if any-->
    <% if @analytic_instance.errors.any? %>
        <div id="error_explanation" class="alert alert-danger" role="alert">
          <h2><%= pluralize(@analytic_instance.errors.count, "error") %> prohibited this analytic_instance from being
            saved:</h2>

          <ul>
            <% @analytic_instance.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <!--Form fields-->
    <div class="field">
      <%= f.label :analytic_server_id, 'Analytic server' %><br>
      <%= f.collection_select(:analytic_server_id, AnalyticServer.all, :id, :name, {prompt: 'Select Analytic Server'}) %>
    </div>

    <div class="field">
      <%= f.label :analytic_id, 'Analytic Type' %><br>
      <%= f.collection_select(:analytic_id, Analytic.where(verified: true), :id, :name, {prompt: 'Select Analytic Type'}, {:disabled => params[:action]=="edit"}) %>
    </div>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>

    <div class="field">
      <%= f.label :notification_id, 'Notification' %><br>

      <% if isOrganization? %>

          <% #### To protect someone edit an analytic instance but he/she does not have permisstion in this notification
             @notifications = Notification.where(:group_user_id => GroupUser.getGroupUserList(session[:org_id], current_user.id))

             isAllowNotification = false
             @notifications.each do |notification|

               if notification.id == @analytic_instance.notification_id
                 isAllowNotification = true
                 break
               end
             end
          %>

          <% if params[:action]!="edit" %>
              <%= f.collection_select(:notification_id, @notifications,:id, :title, {prompt: 'Select Notification'},{:selected => @analytic_instance.notification_id}) %>
          <% else %>
              <% if isAllowNotification %>
                  <%= f.collection_select(:notification_id, @notifications,:id, :title, {prompt: 'Select Notification'},{:selected => @analytic_instance.notification_id}) %>
              <% else %>
                  <%= f.collection_select(:notification_id, Notification.where(:id => @analytic_instance.notification_id),:id, :title,{},:disabled => 'disabled' ) %>
                  <br />
                  <p style="color:red;"> *** You are not allowed editing notification.</p>
              <% end %>
          <% end %>
      <% else %>
          <%= f.collection_select(:notification_id, Notification.where(:user_id => current_user.id), :id, :title,
                                  {prompt: 'Select Notification'},
                                  {:selected => @analytic_instance.notification_id}) %>
      <% end %>
    </div>

    <% if isOrganization? %>
        <%= f.label :group_user_id, 'Created as' %>
        <br>

        <%= f.collection_select(:group_user_id, GroupUser.getGroupUserListSelection(session[:org_id], current_user.id),
                                :id, :title,
                                {:selected => params[:group_user_id]}) %>

        <br/>
    <% end %>

    <!--Submit button-->
    <p>
    <div class="actions">
      <%= f.submit class: "btn btn-success btn-mini" %>
      <%= link_to 'Cancel', :back, :class => "btn btn-danger" %>
    </div>
    </p>
<% end %> <!--Form ends-->

opencctv-web/app/views/analytic_instances/_info.html.erb
<div class="container">
  <h1>
    Analytic instance information

    <% if isOrganization? %>
        <a href="<%=edit_group_user_analytic_instance_path(params[:group_user_id],@analytic_instance)%>" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span> Edit</a>

  <% else %>
        <a href="<%=edit_analytic_instance_path(@analytic_instance)%>" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span> Edit</a>
  <% end %>

  </h1>
  <p>
    <strong>Analytic ID:</strong>
    <%= @analytic_instance.id %>
  </p>
  <p>
    <strong>Name:</strong>
    <%= @analytic_instance.name %>
  </p>
  <p>
    <strong>Analytic Type:</strong>
    <%= @analytic_instance.analytic.name %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= @analytic_instance.description %>
  </p>

  <p>
    <strong>Analytic server id:</strong>
    <%= @analytic_instance.analytic_server_id %>
  </p>
</div>

opencctv-web/app/views/analytic_instances/edit.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Analytic instances', analytic_instances_path %></li>
    <li class="active">Edit analytic instance</li>
  </ol>
</div>

<div class="container">
  <h1>Edit analytic instance details</h1>
  <%= render 'form' %>

  <br>
  <div>
    <strong>Changing analytic instance type:</strong> <br>
    If you need to change the analytic instance type, please
    <%= link_to 'Delete', @analytic_instance, method: :delete, :class => "btn btn-xs btn-danger", data: { confirm: 'Are you sure?' } %>
    and re-create the instance with a new type.
  </div>
</div>

opencctv-web/app/views/analytic_instances/index.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Home', root_path %></li>
    <li class="active">Analytic instances</li>
  </ol>
</div>

<div class="container">
  <h1>
    Listing analytic instances
    <a href="<%= new_analytic_instance_path %>" class="btn btn-success">
      <span class="glyphicon glyphicon-upload"></span> Create new analytic instance</a>
  </h1>


  <% if @analytic_instances.empty? %>
      <p>
      <div class="alert alert-warning">
        Currently no analytic instances are registered with the system.
      </div>
      </p>
  <% else %>
      <div class="media">
        <table class="table table-hover">

          <thead>
          <tr>
            <th>#</th>
            <th>Analytic ID</th>
            <th>Name</th>
            <th>Analytic Type</th>
            <th>Description</th>

            <th colspan="4"></th>
          </tr>
          </thead>

          <tbody>
          <% i = 1 %>
          <% @analytic_instances.each do |analytic_instance| %>
              <tr>
                <td><%= i %></td>
                <td><%= analytic_instance.id %></td>
                <td><%= analytic_instance.name %></td>
                <td><%= analytic_instance.analytic.name %></td>
                <td><%= analytic_instance.description %></td>


                <% if isOrganization? %>

                    <td><%= link_to 'Show', group_user_analytic_instance_path(analytic_instance.group_user_id, analytic_instance), :class => "btn btn-xs btn-default" %></td>
                    <td><%= link_to 'Edit', edit_group_user_analytic_instance_path(analytic_instance.group_user_id, analytic_instance), :class => "btn btn-xs btn-warning" %></td>
                    <td><%= link_to 'Destroy', group_user_analytic_instance_path(analytic_instance.group_user_id, analytic_instance), method: :delete, :class => "btn btn-xs btn-danger", data: {confirm: 'Are you sure?'} %></td>

                <% else %>

<<<<<<< HEAD
                    <% if analytic_instance.status == 0 %>

                        <td><%= link_to 'Start', start_analytic_instance_path(analytic_instance), :class => "btn btn-xs btn-warning" %></td>

                    <%elsif analytic_instance.status == 2 %>

                        <td><%= link_to 'Stop', stop_analytic_instance_path(analytic_instance), :class => "btn btn-xs btn-danger", data: {confirm: 'Are you sure?'} %></td>

                    <%else%>
                        <td><%= link_to 'Pending',"#" ,:class => "btn btn-xs btn-info" %></td>
                    <% end %>

                    <td><%= link_to 'Show', analytic_instance, :class => "btn btn-xs btn-default" %></td>
                    <td><%= link_to 'Edit', edit_analytic_instance_path(analytic_instance), :class => "btn btn-xs btn-warning" %></td>
                    <td><%= link_to 'Destroy', analytic_instance, method: :delete, :class => "btn btn-xs btn-danger", data: {confirm: 'Are you sure?'} %></td>


                <% end %>

              </tr>
              <% i = i + 1 %>
          <% end %>
          </tbody>
        </table>
      </div>
  <% end %>
</div>

opencctv-web/app/views/analytic_instances/new.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Analytic instances', analytic_instances_path %></li>
    <li class="active">New analytic instance</li>
  </ol>
</div>

<div class="container">
  <h1>Create a new analytic instance</h1>
  <%= render 'form' %> <!--Form from _form.html.erb-->
</div>

opencctv-web/app/views/analytic_instances/show.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Analytic instances', analytic_instances_path %></li>
    <li class="active">Analytic instance</li>
  </ol>
</div>

<%= render 'info' %>

<div class="container">
  <p>
    <a href="<%= new_analytic_instance_analytic_instance_stream_path(@analytic_instance)%>" class="btn btn-success"> <span class="glyphicon glyphicon-plus"></span> Add Input Stream </a>
  </p>

  <br/>

  <div class="media">
    <%if @analytic_instance.analytic_instance_streams.empty?%>
        <div class="alert alert-warning">
          Currently no input streams are registered with the analytic instance.
        </div>
    <%else%>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4>Analytic Instance Input Streams</h4>
          </div>
          <div class="media">
            <table class="table table-hover">
              <thead>
              <tr>
                <th>#</th>
                <th>Analytic input stream</th>
                <th>Stream</th>
                <th colspan="3"></th>
              </tr>
              </thead>

              <tbody>
              <% i = 1 %>
              <% @analytic_instance.analytic_instance_streams.each do |input_stream| %>
                  <tr>
                    <td><%= i %></td>
                    <td><%= input_stream.analytic_input_stream.name %></td>
                    <td><%= input_stream.stream.name %></td>

                    <td><%= link_to 'Show', analytic_instance_analytic_instance_stream_path(@analytic_instance,input_stream), class: "btn btn-xs btn-default"%></td>
                    <td><%= link_to 'Edit', edit_analytic_instance_analytic_instance_stream_path(@analytic_instance,input_stream), class: "btn btn-xs btn-warning" %>
                    <td><%= link_to 'Destroy', analytic_instance_analytic_instance_stream_path(@analytic_instance,input_stream), method: :delete, class: "btn btn-xs btn-danger", data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                  <% i = i + 1 %>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
    <%end%>
  </div>

  <div class="media">


    <%if @analytic_configs.empty?%>
        <div class="alert alert-warning">
          Currently no analytic  config files are upload with the analytic.
        </div>
    <%else%>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4>Analytic Instance Input Streams</h4>
          </div>
          <div class="media">
            <table class="table table-hover">
              <thead>
              <tr>
                <th>#</th>
                <th>File name</th>
                <th colspan="2"></th>
              </tr>
              </thead>

              <tbody>
              <% i = 1 %>
              <% @analytic_configs.each do |analytic_instance_config| %>
                  <tr>
                    <td><%= i %></td>
                    <td><%= analytic_instance_config.fileName %></td>
                    <td><%= link_to 'Show', analytic_instance_analytic_instance_config_path(@analytic_instance.id, analytic_instance_config.id), class: "btn btn-xs btn-default"%></td>
                    <td><%= link_to 'Edit', edit_analytic_instance_analytic_instance_config_path(@analytic_instance.id, analytic_instance_config.id), class: "btn btn-xs btn-warning" %>
                    <td><%#= link_to 'Destroy', analytic_instance_analytic_instance_stream_path(@analytic_instance,input_stream), method: :delete, class: "btn btn-xs btn-danger", data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                  <% i = i + 1 %>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
    <%end%>
  </div>

</div>