opencctv-web/config/routes.rb
Rails.application.routes.draw do

  resources :analytic_servers

  resources :analytic_instance_streams do
    resources :analytic_instance_stream_configs do
    end
  end

resources :analytic_instances do
  resources :analytic_instance_configs do
  end
end
  get 'test/createTest', to: "test#createTest"
  get 'test/clearTest'

  get 'mobile_notifications/index'

  get 'mobile_notifications/new'

  get 'mobile_notifications/create'

  get 'mobile_notifications/edit'

  get 'mobile_notifications/update'

  get 'google_projects/index'

  get 'google_projects/new'

  get 'google_projects/show'

  get 'google_projects/edit'

  get 'api_sessions/sign_in'

  get 'api_sessions/sign_out'

  get 'session/sign_out'

  get 'session/sign_in'

  get  '/org/indexUser', to: "orgs#indexUser", as: 'org_users'
  delete  '/org/removeUser/:user_id', to: "orgs#removeUser", as: 'org_remove_user'

  post '/orgs/login/:org_id', to: "orgs#loginAsOrg", as: 'login_as_org'
  delete '/orgs/login', to: "orgs#loginAsUser", as: 'login_as_user'

  post '/org_group_users/:group_user_id/:org_user_id', to: "org_group_users#create", as: 'org_group_user'
  delete '/org_group_users/:group_user_id/:org_user_id', to: "org_group_users#destroy", as: 'destroy_org_group_user'

  post '/requests/:org_id', to: "requests#create", as: 'new_org_request'
  get  '/requests/admin', to: "requests#indexAdmin", as: 'org_requests'

  resources :requests

  resources :group_users do
    resources :vmses do
    end
  end

  resources :group_users do
    resources :analytic_instances do
    end
  end

  resources :group_users do
    resources :notifications do
    end
  end

  devise_for :users

  resources :group_users

  resources :orgs

  resources :notifications

  resources :vms_connectors

  resources :vmses do
    resources :cameras do
      resources :streams
    end
  end

  resources :analytics do
    resources :analytic_input_streams
  end

  get '/analytic_instance/:id/start', to: "analytic_instances#startAnalytic", as: 'start_analytic_instance'
  get '/analytic_instance/:id/stop', to: "analytic_instances#stopAnalytic", as: 'stop_analytic_instance'

  resources :analytic_instances do
    resources :analytic_instance_streams
  end

  resources :open_cctv_servers

  get 'about/index'

  root 'about#index'

  get '/download/vms_connector/:filename' => 'download#vms_connector', as: :vms_connector_download

  get '/download/analytic/:filename' => 'download#analytic', as: :analytic_download

  get '/open_cctv_servers/:id/start' => 'open_cctv_servers#start_server', as: :open_cctv_servers_start

  get '/open_cctv_servers/:id/stop' => 'open_cctv_servers#stop_server', as: :open_cctv_servers_stop

  get '/open_cctv_servers/:id/restart' => 'open_cctv_servers#restart_server', as: :open_cctv_servers_restart

  post '/api/google_tokens/register'   => 'google_tokens#register'
  post '/api/google_tokens/deregister' => 'google_tokens#deregister'

  post '/api/users/sign_in'  => 'api_sessions#sign_in'
  post '/api/users/sign_out' => 'api_sessions#sign_out'

  resources :google_projects
  resources :mobile_notifications

end

opencctv-web/app/models/open_cctv_server.rb
class OpenCctvServer < ActiveRecord::Base

  validates :name, presence: true
  validates :host, presence: true
  validates :port, presence: true

  def send_to_server(message_type)

    msg_details = nil
    reply = nil
    error_reply = reply = "<?xml version=\"1.0\" encoding=\"utf-8\"?><opencctvmsg><opencctvmsg><type>Error</type><content>Connecting to OpenCCTV Sever on #{self.host}:#{self.port} Failed</content><serverstatus>Unknown</serverstatus><serverpid>0</serverpid></opencctvmsg>"

    context = ZMQ::Context.new(1)
    requester = nil

    if context
      #Create a request type socket
      requester = context.socket(ZMQ::REQ)

      #Set the socket options
      requester.setsockopt(ZMQ::SNDTIMEO, 10000) # A 10 second timeout is set for send
      requester.setsockopt(ZMQ::RCVTIMEO, 10000) # A 10 second timeout is set for receive
      requester.setsockopt(ZMQ::LINGER,0)

      #Connects to the socket
      rc = requester.connect("tcp://#{self.host}:#{self.port}")
      message = "<?xml version=\"1.0\" encoding=\"utf-8\"?><opencctvmsg><type>#{message_type}</type></opencctvmsg>"

      #Send a request
      rc = requester.send_string(message) unless zmq_error_check(rc)

      #Receive reply
      rc = requester.recv_string(reply) unless zmq_error_check(rc)
    end

    #Close the socket and terminate the ZMQ context
    requester.close unless requester.nil?
    context.terminate

    reply.nil? ? msg_details = parse_reply(error_reply) : msg_details = parse_reply(reply)
    return msg_details

  end

  private
  def parse_reply (xml_string)
    #Example reply messages :
    #successfull : <?xml version="1.0" encoding="utf-8"?><opencctvmsg><type>StartReply</type><content>OpenCCTV Server Started</content><serverstatus>Running</serverstatus><serverpid>17287</serverpid></opencctvmsg>
    #failed : <?xml version="1.0" encoding="utf-8"?> <opencctvmsg><type>Error</type><content>Unknown message type received</content><serverstatus>Unknown</serverstatus><serverpid>0</serverpid></opencctvmsg>

    type = nil
    content = nil
    server_status = nil
    server_pid = nil

    msg_details = {}


    if(!xml_string.nil? && xml_string.start_with?("<"))
      doc = Nokogiri::XML(xml_string)
      type = doc.xpath('//opencctvmsg//type')[0].content.to_s.strip
      content = doc.xpath('//opencctvmsg//content')[0].content.to_s.strip
      server_status = doc.xpath('//opencctvmsg//serverstatus')[0].content.to_s.strip
      server_pid = doc.xpath('//opencctvmsg//serverpid')[0].content.to_s.strip

      msg_details[:type] = type
      msg_details[:content] = content
      msg_details[:server_status] = server_status
      msg_details[:server_pid] = server_pid
    end

    return msg_details

  end

  def zmq_error_check(rc)
    if ZMQ::Util.resultcode_ok?(rc)
      false
    else
      STDERR.puts "Operation failed, errno [#{ZMQ::Util.errno}] description [#{ZMQ::Util.error_string}]"
      true
    end
  end

end

opencctv-web/app/controllers/open_cctv_servers_controller.rb
class OpenCctvServersController < ApplicationController
  before_action :set_open_cctv_server, only: [:show, :edit, :update, :destroy, :start_server, :stop_server, :restart_server]
  before_action :authenticate_user!
  before_action :isOpenCCTVPageAdmin?
  respond_to :html

  # GET /open_cctv_servers
  def index
    @open_cctv_server = OpenCctvServer.last
    if (!@open_cctv_server.nil?)
      request_server_status
    end
    respond_with(@open_cctv_server)
  end

  # GET /open_cctv_servers/1
  def show
    #@open_cctv_server = OpenCctvServer.find(params[:id])
    @open_cctv_server = OpenCctvServer.last
    if (!@open_cctv_server.nil?)
      request_server_status
    end
    respond_with(@open_cctv_server)
  end

  # GET /open_cctv_servers/new
  def new
    @open_cctv_server = OpenCctvServer.new
    @open_cctv_server.name = 'OpenCCTV Server'
    @open_cctv_server.host = '127.0.0.1'
    @open_cctv_server.port = 4444
    respond_with(@open_cctv_server)
  end

  # GET /open_cctv_servers/1/edit
  def edit
  end

  # POST /open_cctv_servers
  def create
    @open_cctv_server = OpenCctvServer.new(open_cctv_server_params)
    @open_cctv_server.save
    respond_with(@open_cctv_server)
  end

  # PATCH/PUT /open_cctv_servers/1
  def update
    if(@open_cctv_server.status =='Running')
      flash[:alert] = 'It is not possible to edit the Open CCTV Server details while it is running'
    else
      @open_cctv_server.status = 'Unknown'
      @open_cctv_server.update(open_cctv_server_params)
      respond_with(@open_cctv_server)
    end
  end

  # DELETE /open_cctv_servers/1
  def destroy
    @open_cctv_server.destroy
    respond_with(@open_cctv_server)
  end

  def start_server
    exec_server_cmd('StartRequest')
  end

  def stop_server
    exec_server_cmd('StopRequest')
  end

  def restart_server
    exec_server_cmd('RestartRequest')
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_open_cctv_server
    @open_cctv_server = OpenCctvServer.find(params[:id])

  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def open_cctv_server_params
    params.require(:open_cctv_server).permit(:name, :host, :port, :status, :pid)
  end

  def exec_server_cmd(command)
    server_reply = @open_cctv_server.send_to_server(command)
    #flash[:alert] = "server_reply : #{server_reply}"

    @open_cctv_server.update_attribute(:status, server_reply[:server_status])
    @open_cctv_server.update_attribute(:pid, server_reply[:server_pid])

    if(server_reply[:type].eql? 'Error')
      flash.now[:error] = "#{server_reply[:content]}"
    end
    redirect_to open_cctv_server_path
  end

  def request_server_status
    server_reply = @open_cctv_server.send_to_server('StatusRequest')
    #flash[:alert] = "server_reply : #{server_reply}"

    @open_cctv_server.update_attribute(:status, server_reply[:server_status])
    @open_cctv_server.update_attribute(:pid, server_reply[:server_pid])

    if(server_reply[:type].eql? 'Error')
      flash.now[:error] = "#{server_reply[:content]}"
    end
  end
end

opencctv-web/app/helpers/open_cctv_servers_helper.rb
module OpenCctvServersHelper

  def sendToServerWithData(openCctvServer, message_type, aIID, aSID)

    puts openCctvServer.port
    puts openCctvServer.host

    msg_details = nil
    reply = nil
    error_reply = reply = "<?xml version=\"1.0\" encoding=\"utf-8\"?><opencctvmsg><opencctvmsg><type>Error</type><content>Connecting to OpenCCTV Sever on #{openCctvServer.host}:#{openCctvServer.port} Failed</content><serverstatus>Unknown</serverstatus><serverpid>0</serverpid></opencctvmsg>"

    context = ZMQ::Context.new(1)
    requester = nil

    if context
      #Create a request type socket
      requester = context.socket(ZMQ::REQ)

      #Set the socket optionst
      requester.setsockopt(ZMQ::SNDTIMEO, 10000) # A 10 second timeout is set for send
      requester.setsockopt(ZMQ::RCVTIMEO, 10000) # A 10 second timeout is set for receive
      requester.setsockopt(ZMQ::LINGER,0)

      #Connects to the socket
      rc = requester.connect("tcp://#{openCctvServer.host}:#{openCctvServer.port}")
      message = "<?xml version=\"1.0\" encoding=\"utf-8\"?><opencctvmsg><type>#{message_type}</type><AIId>#{aIID}</AIId><ASId>#{aSID}</ASId></opencctvmsg>"

      #Send a request
      rc = requester.send_string(message) unless zmq_error_check(rc)

      #Receive reply
      rc = requester.recv_string(reply) unless zmq_error_check(rc)
    end

    #Close the socket and terminate the ZMQ context
    requester.close unless requester.nil?
    context.terminate

    puts reply

    reply.nil? ? msg_details = parse_reply(error_reply) : msg_details = parse_reply(reply)
    return msg_details

  end


  private
  def parse_reply (xml_string)
    #Example reply messages :
    #successfull : <?xml version="1.0" encoding="utf-8"?><opencctvmsg><type>StartReply</type><content>OpenCCTV Server Started</content><serverstatus>Running</serverstatus><serverpid>17287</serverpid></opencctvmsg>
    #failed : <?xml version="1.0" encoding="utf-8"?> <opencctvmsg><type>Error</type><content>Unknown message type received</content><serverstatus>Unknown</serverstatus><serverpid>0</serverpid></opencctvmsg>

    #<?xml version="1.0" encoding="utf-8"?><opencctvmsg><type>StopReply</type><content>ok</content><serverstatus>Running</serverstatus><serverpid>9999</serverpid></opencctvmsg>

    type = nil
    content = nil
    server_status = nil
    server_pid = nil

    msg_details = {}

    if(!xml_string.nil? && xml_string.start_with?("<"))
      doc = Nokogiri::XML(xml_string)
      type = doc.xpath('//opencctvmsg//type')[0].content.to_s.strip
      content = doc.xpath('//opencctvmsg//content')[0].content.to_s.strip
      server_status = doc.xpath('//opencctvmsg//serverstatus')[0].content.to_s.strip
      server_pid = doc.xpath('//opencctvmsg//serverpid')[0].content.to_s.strip

      msg_details[:type] = type
      msg_details[:content] = content
      msg_details[:server_status] = server_status
      msg_details[:server_pid] = server_pid
    end

    return msg_details

    end

    def zmq_error_check(rc)
    if ZMQ::Util.resultcode_ok?(rc)
      false
    else
      STDERR.puts "Operation failed, errno [#{ZMQ::Util.errno}] description [#{ZMQ::Util.error_string}]"
      true
    end
  end


end

opencctv-web/app/views/open_cctv_servers/_form.html.erb
<%= form_for(@open_cctv_server) do |f| %>
  <!--Report errors if any-->
  <% if @open_cctv_server.errors.any? %>
      <div id="error_explanation" class="alert alert-danger" role="alert">
      <h2><%= pluralize(@open_cctv_server.errors.count, "error") %> prohibited this open_cctv_server from being saved:</h2>

      <ul>
      <% @open_cctv_server.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--Form fields-->
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name%>
  </div>
  <div class="field">
    <%= f.label :host %><br>
    <%= f.text_field :host%>
  </div>
  <div class="field">
    <%= f.label :port %><br>
    <%= f.number_field :port%>
  </div>

  <!--Submit button-->
  <p>
  <div class="actions">
    <%= f.submit 'Save Connection Details', :class => 'btn btn-success btn-mini'%>
    <%= link_to 'Cancel', open_cctv_servers_path, :class => "btn btn-danger" %>
  </div>
  </p>
<% end %> <!--Form ends-->

opencctv-web/app/views/open_cctv_servers/_info.html.erb
<div class="container">

  <div class="panel panel-default">
    <div class="panel-heading">
      <h1>OpenCCTV Server Information</h1>
    </div>
    <div class="panel-body">
      <div class="media">
        <div class="media-body col-sm-12">
          <p>
            <strong>Connection Name:</strong>
            <%= @open_cctv_server.name %>
          </p>
          <p>
            <strong>Host:</strong>
            <%= @open_cctv_server.host %>
          </p>
          <p>
            <strong>Port:</strong>
            <%= @open_cctv_server.port %>
          </p>
          <p>
            <strong>Status:</strong>
            <%if @open_cctv_server.status.nil? || @open_cctv_server.status.empty? || @open_cctv_server.status.blank?%>
                Unknown
            <%else%>
                <%= @open_cctv_server.status %>
            <%end%>
          </p>
          <p>
            <strong>PID:</strong>
            <%if @open_cctv_server.pid.nil? || @open_cctv_server.pid.blank?%>
                NA
            <%else%>
                <%= @open_cctv_server.pid %>
            <%end%>
          </p>
          <p>
            <%if (@open_cctv_server.status.eql? 'Stopped') || (@open_cctv_server.status.eql? 'Unknown')%>
                <%= link_to 'Edit', edit_open_cctv_server_path(@open_cctv_server), :class => "btn btn-xs btn-warning", data: { confirm: 'This may need restarting the OpenCCTV Server, do you want to continue?' }%> |
                <%= link_to 'Delete', @open_cctv_server, method: :delete, :class => "btn btn-xs btn-danger", data: { confirm: 'Do you want to delete the connection to the OpenCCTV Server?' } %>
            <%end%>
          </p>
        </div>
      </div>
    </div>
  </div>

  <br/>
  <% if @open_cctv_server.status.eql? 'Stopped' %>
      <%= link_to 'Start server', open_cctv_servers_start_path(@open_cctv_server), :class => "btn btn-success"%>
  <%elsif @open_cctv_server.status.eql? 'Running'%>
      <%= link_to 'Stop server', open_cctv_servers_stop_path(@open_cctv_server), :class => "btn btn-danger"%>
      <%= link_to 'Check Server Status', open_cctv_server_path(@open_cctv_server), :class => "btn btn-success"%>
  <%else%>
      <%= link_to 'Restart Server', open_cctv_servers_restart_path(@open_cctv_server), :class => "btn btn-warning"%>
      <%= link_to 'Check Server Status', open_cctv_server_path(@open_cctv_server), :class => "btn btn-success"%>
  <%end%>

</div>

opencctv-web/app/views/open_cctv_servers/edit.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Open CCTV Server', open_cctv_server_path(@open_cctv_server) %></li>
    <li class="active">Edit OpenCCTV Server</li>
  </ol>
</div>

<div class="container">
  <h1>Editing OpenCCTV Server connection</h1>
  <%= render 'form' %>
</div>

opencctv-web/app/views/open_cctv_servers/index.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Home', root_path %></li>
    <li class="active">OpenCCTV Server</li>
  </ol>
</div>

<%if @open_cctv_server.nil?%>
  <div class="container">
    <a href="<%=new_open_cctv_server_path%>" class="btn btn-success"> <span class="glyphicon glyphicon-plus"></span>Register a Connection to OpenCCTV Server</a>
    <br/>
    <br/>

    <div class="alert alert-warning">
      Currently no OpenCCTV Server is registered with the system.
    </div>
  </div>
<%else%>
  <%= render 'info' %>
<%end%>

opencctv-web/app/views/open_cctv_servers/new.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Open CCTV Server', open_cctv_servers_path%></li>
    <li class="active">New Open CCTV Server</li>
  </ol>
</div>

<div class="container">
  <h1>New OpenCCTV Server connection</h1>
  <%= render 'form' %>
</div>

opencctv-web/app/views/open_cctv_servers/show.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Home', root_path %></li>
    <li class="active">OpenCCTV Server</li>
  </ol>
</div>

<%if @open_cctv_server.nil?%>
    <div class="container">
      <a href="<%=new_open_cctv_server_path%>" class="btn btn-success"> <span class="glyphicon glyphicon-plus"></span>Register a Connection to OpenCCTV Server</a>
      <br/>
      <br/>

      <div class="alert alert-warning">
        Currently no OpenCCTV Server is registered with the system.
      </div>
    </div>
<%else%>
    <%= render 'info' %>
<%end%>


<%#= render 'info' %>