opencctv-web/config/routes.rb
Rails.application.routes.draw do

  resources :analytic_servers

  resources :analytic_instance_streams do
    resources :analytic_instance_stream_configs do
    end
  end

resources :analytic_instances do
  resources :analytic_instance_configs do
  end
end
  get 'test/createTest', to: "test#createTest"
  get 'test/clearTest'

  get 'mobile_notifications/index'

  get 'mobile_notifications/new'

  get 'mobile_notifications/create'

  get 'mobile_notifications/edit'

  get 'mobile_notifications/update'

  get 'google_projects/index'

  get 'google_projects/new'

  get 'google_projects/show'

  get 'google_projects/edit'

  get 'api_sessions/sign_in'

  get 'api_sessions/sign_out'

  get 'session/sign_out'

  get 'session/sign_in'

  get  '/org/indexUser', to: "orgs#indexUser", as: 'org_users'
  delete  '/org/removeUser/:user_id', to: "orgs#removeUser", as: 'org_remove_user'

  post '/orgs/login/:org_id', to: "orgs#loginAsOrg", as: 'login_as_org'
  delete '/orgs/login', to: "orgs#loginAsUser", as: 'login_as_user'

  post '/org_group_users/:group_user_id/:org_user_id', to: "org_group_users#create", as: 'org_group_user'
  delete '/org_group_users/:group_user_id/:org_user_id', to: "org_group_users#destroy", as: 'destroy_org_group_user'

  post '/requests/:org_id', to: "requests#create", as: 'new_org_request'
  get  '/requests/admin', to: "requests#indexAdmin", as: 'org_requests'

  resources :requests

  resources :group_users do
    resources :vmses do
    end
  end

  resources :group_users do
    resources :analytic_instances do
    end
  end

  resources :group_users do
    resources :notifications do
    end
  end

  devise_for :users

  resources :group_users

  resources :orgs

  resources :notifications

  resources :vms_connectors

  resources :vmses do
    resources :cameras do
      resources :streams
    end
  end

  resources :analytics do
    resources :analytic_input_streams
  end

  get '/analytic_instance/:id/start', to: "analytic_instances#startAnalytic", as: 'start_analytic_instance'
  get '/analytic_instance/:id/stop', to: "analytic_instances#stopAnalytic", as: 'stop_analytic_instance'

  resources :analytic_instances do
    resources :analytic_instance_streams
  end

  resources :open_cctv_servers

  get 'about/index'

  root 'about#index'

  get '/download/vms_connector/:filename' => 'download#vms_connector', as: :vms_connector_download

  get '/download/analytic/:filename' => 'download#analytic', as: :analytic_download

  get '/open_cctv_servers/:id/start' => 'open_cctv_servers#start_server', as: :open_cctv_servers_start

  get '/open_cctv_servers/:id/stop' => 'open_cctv_servers#stop_server', as: :open_cctv_servers_stop

  get '/open_cctv_servers/:id/restart' => 'open_cctv_servers#restart_server', as: :open_cctv_servers_restart

  post '/api/google_tokens/register'   => 'google_tokens#register'
  post '/api/google_tokens/deregister' => 'google_tokens#deregister'

  post '/api/users/sign_in'  => 'api_sessions#sign_in'
  post '/api/users/sign_out' => 'api_sessions#sign_out'

  resources :google_projects
  resources :mobile_notifications

end

opencctv-web/app/models/group_user.rb
class GroupUser < ActiveRecord::Base
  #has_many :group_cans, dependent: :destroy
  #has_many :roles, through: :group_cans

  belongs_to :org
  belongs_to :role

  has_many :org_group_users, dependent: :destroy
  has_many :org_users, through: :org_group_users

  #has_many :cameras, through: :org_group_users
  has_many :vmses, dependent: :destroy
  has_many :analytic_instances, dependent: :destroy
  has_many :notifications, dependent: :destroy



  def self.getGroupUserList(org_id, user_id)
    return self.joins(:org_users).where(:org_id => org_id, :org_users => {:user_id => user_id}).pluck(:group_user_id)
  end

  def self.getGroupUserListSelection(org_id, user_id)
    return self.joins(:org_users).where(:org_id => org_id, :org_users => {:user_id => user_id})
        .select('group_users.id', 'group_users.title')
  end


  def self.getGroupListPerOrg(org_id)
    return self.where(:org_id => org_id)
  end

end

opencctv-web/app/controllers/group_users_controller.rb
class GroupUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :isOrganizationPageAdmin?

  before_action :set_group_user, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index

    @group_users = GroupUser.getGroupListPerOrg(session[:org_id])
    respond_with(@group_users)
  end

  def show

    @addedUserLists = User.joins(org_users: :group_users).where(:org_users => {:org_id => session[:org_id]}, :group_users =>{:id => @group_user.id}).select('org_users.id','users.email')

    @userLists = User.joins(:orgs).where(:orgs => {:id => session[:org_id]}).where.not(:users => {:id => @addedUserLists.ids}).select('org_users.id','users.email')

    @org_group_user = OrgGroupUser.new
    respond_with(@group_user)
  end

  def new
    @group_user = GroupUser.new
    respond_with(@group_user)
  end

  def edit
  end

  def create
    @group_user = GroupUser.new(:title => params[:group_user][:title], :detail => params[:group_user][:detail],
                                :org_id => session[:org_id], :role_id => ApplicationController::ROLE_RESOURCE_ADMIN)
    @group_user.save
    respond_with(@group_user)
  end

  def update
    @group_user.update(group_user_params)
    respond_with(@group_user)
  end

  def destroy
    @group_user.destroy
    respond_with(@group_user)
  end

  def addUserGroup

  end

  private
    def set_group_user
      @group_user = GroupUser.where(:id => params[:id]).first()
    end

    def group_user_params
      params.require(:group_user).permit(:title, :detail)
    end
end

opencctv-web/app/helpers/group_users_helper.rb
module GroupUsersHelper
end

opencctv-web/app/views/group_users/_form.html.erb
<%= form_for(@group_user) do |f| %>
    <% if @group_user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@group_user.errors.count, "error") %> prohibited this group_user from being saved:</h2>

          <ul>
            <% @group_user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :detail %><br>
      <%= f.text_area :detail %>
    </div>

    <!--Submit button-->

    <p>
    <div class="actions">
      <%= f.submit class: "btn btn-success btn-mini" %>
      <%= link_to 'Cancel', @group_user, :class => "btn btn-danger" %>
    </div>
    </p>
<% end %>

opencctv-web/app/views/group_users/_info.html.erb
<div class="container">
  <h1>
    Group information

    <a href="<%= edit_group_user_path(@group_user) %>" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span>
      Edit</a>

  </h1>

  <p>
    <strong>Title:</strong>
    <%= @group_user.title %>
  </p>

  <p>
    <strong>Detail:</strong>
    <%= @group_user.detail %>
  </p>

</div>

opencctv-web/app/views/group_users/edit.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Groups', group_users_path %></li>
    <li class="active">Edit group</li>
  </ol>
</div>


<div class="container">
  <h1>Editing group_user</h1>

  <%= render 'form' %>

</div>

opencctv-web/app/views/group_users/index.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Home', root_path %></li>
    <li class="active">Groups</li>
  </ol>
</div>

<div class="container">
  <h1>
    All created groups
    <a href="<%= new_group_user_path %>" class="btn btn-success"> <span class="glyphicon glyphicon-upload"></span>
      Create a
      group</a>
  </h1>


  <br/>

  <div class="media">
    <% if @group_users.empty? %>
        <div class="alert alert-warning">
          Currently no groups are created with this organization.
        </div>
    <% else %>
        <table class="table table-hover">
          <thead>
          <tr>
            <th>#</th>
            <th>Title</th>
            <th>Detail</th>

            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% i = 1 %>
          <% @group_users.each do |group_user| %>
              <tr>
                <td><%= i %></td>
                <td><%= group_user.title %></td>
                <td><%= group_user.detail %></td>

                <td><%= link_to 'Show', group_user, :class => "btn btn-xs btn-default" %></td>
                <td><%= link_to 'Edit', edit_group_user_path(group_user), :class => "btn btn-xs btn-warning" %></td>
                <td><%= link_to 'Destroy', group_user, method: :delete, :class => "btn btn-xs btn-danger", data: {confirm: 'Are you sure?'} %></td>
              </tr>
              <% i = i + 1 %>
          <% end %>
          </tbody>
        </table>

    <% end %>
  </div>
</div>

opencctv-web/app/views/group_users/new.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Groups', group_users_path %></li>
    <li class="active">New group</li>
  </ol>
</div>

<div class="container">

  <h1>New group</h1>

  <%= render 'form' %>

</div>

opencctv-web/app/views/group_users/show.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Groups', group_users_path %></li>
    <li class="active">Group</li>
  </ol>
</div>

<%= render 'info' %>

<br/>


<div class="container">

  <div class="media">
    <% if @userLists.empty? %>
        <div class="alert alert-warning">
          Currently no user in this group.
        </div>
    <% else %>

        <div class="panel panel-default">
          <div class="panel-heading">
            <h4>Listing users in group</h4>
          </div>

            <table class="table table-hover">

              <thead>
              <tr>
                <th>#</th>
                <th>Email</th>
              </tr>
              </thead>

              <tbody>
              <% i = 1 %>
              <% @userLists.each do |userList| %>
                  <tr>
                    <td><%= i %></td>
                    <td><%= userList.email %></td>

                    <td><%= link_to 'Add', org_group_user_path(@group_user.id, userList.id), method: :post, class: "btn btn-success"%></td>
                  </tr>
                  <% i = i + 1 %>
              <% end %>
              </tbody>
            </table>
        </div>
    <% end %>
  </div>


  <div class="media">
    <% if @addedUserLists.empty? %>
        <div class="alert alert-warning">
          Currently no added user in this group.
        </div>
    <% else %>

        <div class="panel panel-default">
          <div class="panel-heading">
            <h4>Listing added users in group</h4>
          </div>
            <table class="table table-hover">
              <thead>
              <tr>
                <th>#</th>
                <th>Email</th>
              </tr>
              </thead>
              <tbody>
              <% i = 1 %>
              <% @addedUserLists.each do |userList| %>
                  <tr>
                    <td><%= i %></td>
                    <td><%= userList.email %></td>

                    <td><%= link_to 'Remove', destroy_org_group_user_path(@group_user.id, userList.id), method: :delete, class: "btn btn-xs btn-danger" %></td>
                  </tr>
                  <% i = i + 1 %>
              <% end %>
              </tbody>
            </table>
        </div>
    <% end %>
  </div>
</div>